name: Build my gitbook and deploy to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : ${{ github.repository_owner }}
      USER_EMAIL  : ${{ github.repository_owner }}@users.noreply.github.com
      BOOK_DIR    : book_sources

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Build and Deploy
      uses: onejar99/gitbook-build-publish-action@v1.0.3